version: '2'
services:
    pratiche02-app:
        image: pratiche02
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pratiche02-mysql:3306/pratiche02?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    pratiche02-mysql:
        extends:
            file: mysql.yml
            service: pratiche02-mysql
